version: "3.4"
services:
  redis:
    image: redis
    volumes:
      - ./data/redis:/data
  web:
    build: .
    user: root
    privileged: true
    image: pi-air-quality-monitor
    # devices:
    #   - "/dev/mem:/dev/mem"
    environment:
        - REDIS_HOST=redis
        - PORT=8000
    volumes:
      - ./src:/code
    depends_on:
      - "redis"
    ports:
      - "8000:8000"
